# Generated by Django 5.2.17 on 2026-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlockDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('decision', models.CharField(choices=[('unblocked', 'Unblocked'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=20)),
                ('source', models.CharField(default='FIREWALL', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
