# Generated by Django 5.2.17 on 2026-09-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipblockdecision',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('unblocked', 'Unblocked'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=20),
        ),
    ]
